<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Crimson.Core\Crimson.Core.csproj" />
      <ProjectReference Include="..\Crimson.Math\Crimson.Math.csproj" />
      <ProjectReference Include="..\Crimson.Graphics\Crimson.Graphics.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="piko.SDL3" Version="0.0.5" />
    </ItemGroup>

</Project>
