<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Crimson.Audio\Crimson.Audio.csproj" />
    <ProjectReference Include="..\Crimson.Core\Crimson.Core.csproj" />
    <ProjectReference Include="..\Crimson.Graphics\Crimson.Graphics.csproj" />
    <ProjectReference Include="..\Crimson.Input\Crimson.Input.csproj" />
    <ProjectReference Include="..\Crimson.Math\Crimson.Math.csproj" />
    <ProjectReference Include="..\Crimson.Physics\Crimson.Physics.csproj" />
    <ProjectReference Include="..\Crimson.Platform\Crimson.Platform.csproj" />
  </ItemGroup>
</Project>
