<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="piko.SDL3" Version="0.0.5" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Crimson.Core\Crimson.Core.csproj" />
    <ProjectReference Include="..\Crimson.Math\Crimson.Math.csproj" />
  </ItemGroup>
</Project>
