<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <Content Include="*.so" CopyToOutputDirectory="Always" />
        <Content Include="*.so.*" CopyToOutputDirectory="Always" />
        <Content Include="*.dll" CopyToOutputDirectory="Always" />
        <Content Include="*.dylib" CopyToOutputDirectory="Always" />
        <!--<Content Include="runtimes/**/*" CopyToOutputDirectory="Always" />-->
    </ItemGroup>

</Project>
